### ISSUE TITLE
Decide which date fields on Litter should be in "list_editable"

### ISSUE THREAD

**Issue by cxrodgers** [cxrodgers/MouseColony#15]
Right now it's "weaned" and "checked", but not the others, for some reason. If they are all editable it takes up too much screen space.

**Comment by danieldkato** [comment]
I think that making a field list_editable is most useful for fields the user might want to edit in batches (e.g. if someone has to sac a bunch of mice on the same day, it would be useful to be able to go to the MouseAdmin list view and hit the "today" button a bunch of times without having to navigate to another page). Given this, maybe we should prioritize including the fields that we're most likely to update for multiple litters in a single session. 

It seems relatively likely that we'll want to check multiple litters in one day. It seems less likely that we'll have to wean multiple litters in one day (a litter should, in principle, be weaned on exactly P21, so we should only wean multiple litters on the same day if the litters were born on exactly the same date). With toe clipping, there's a little bit more leeway, so we might toe clip a batch of litters in one day. 

So perhaps we should make "checked" and "toe clipped" editable but not "weaned"?

**Comment by cxrodgers** [comment]
Agreed, definitely "checked". "Toe clipped" is a maybe because I usually go to the litter page anyway in order to create the mouse objects at this time. "Weaned" seems unnecessary, as you are usually creating Cage objects and so on at this time anyway.

**Comment by danieldkato** [comment]
Good call, "toe clipped" does seem unnecessary given how we're most likely to use the DB at toe clipping.

**Comment by cxrodgers** [comment]
done 614a547
