### ISSUE TITLE
Exclude DOB from mouse inline?

### ISSUE THREAD

**Issue by danieldkato** [cxrodgers/MouseColony#16]
There are two main places where we'll see the mouse inline: 1) when we're adding mice to a litter in the litter admin, and 2) when we're looking at the occupants of a cage. 

For case 1), we don't need the DOB in the mouse inline because they all have the same DOB as the litter. In case 2), the age of the mice is given in mouse info. So we probably don't need DOB in the mouse inline.

**Comment by danieldkato** [comment]
Implemented by commit db8f5f8

**Comment by danieldkato** [comment]
Reverted commit because on second thought, after reading Chris' SOP for migrating mice to the database for the first time, having DOB in the MouseInline might be useful, e.g., for assigning DOBs to mice with no litter info in a non-breeding cage.

**Comment by cxrodgers** [comment]
Hm, yeah, seems like we'll use this a lot for importing. Unless we really need the space I'd say leave it. But we may at some point really need the space.

**Comment by cxrodgers** [comment]
This is moot because we no longer show an inline for regular mice, and for the pup inline it is not shown and not necessary
