### ISSUE TITLE
Automatically sync Mouse dob field with auto_dob if available

### ISSUE THREAD

**Issue by danieldkato** [cxrodgers/MouseColony#18]
Mouse currently has dob (a regular Django DateField) and auto_dob (a custom method that returns the dob of the parent litter if one exists). 

For the most part, we will know when a mouse was born by looking at when its litter of origin was born. This is what auto_dob is for. For some cases, however, we may not have the litter information, and we may want to manually specify the birth date of a particular mouse. For these cases, we've retained dob, which is a regular Django DateField that can be manually edited in the change page for an individual mouse. 

The issue now is that all mice have the manual dob field - including the ones for whom we have an auto_dob from the litter. For those mice that do have an auto_dob, the attributes dob and auto_dob should match; otherwise, one can imagine a situation where a mouse is given an auto_dob, but then when a user navigates to that mouse's individual change page, the manual dob field is confusingly blank. 

We can accomplish this by overriding Mouse's save() method so that when a user is adding mice from the litter admin and presses the save button, Mouse's save() method checks if the mouse has a litter, and if so, sets the mouse's dob DateField to the litter's dob (this is the same approach used in issue #13 to automatically set a litter's proprietor to the proprietor of the breeding cage it came from).

**Comment by danieldkato** [comment]
Realized that this is the second half of issue #9

**Comment by danieldkato** [comment]
Commit 0e383a4 makes it so that when you add mice from the litter admin then press the "save" or "save and continue editing" buttons, the newly added mice get their dob from the litter dob if a litter is available.

**Comment by cxrodgers** [comment]
Great! Sounds like you can close it

**Comment by danieldkato** [comment]
Yaay!
