### ISSUE TITLE
Add custom sacked filter that hides sacked mice in MouseAdmin list view

### ISSUE THREAD

**Issue by danieldkato** [cxrodgers/MouseColony#31]

**Comment by danieldkato** [comment]
This change implemented in commit 01005a3

**Comment by cxrodgers** [comment]
Cool, looks good. I had to make a couple of changes in dd58b43 .
1. I had never seen the _("text") construction before. Is that for translating things? Whatever it is, it was not working, I think we need to import some function as _ before using this. Could be a Python version thing.
2. sackDate -> sack_date

Now works great

**Comment by cxrodgers** [comment]
https://docs.djangoproject.com/en/1.9/topics/i18n/translation/#standard-translation

**Comment by danieldkato** [comment]
Aaah OK I probably imported with an alias in my own db's admin  then forgot
to copy the import statement over into the new db's admin.
