### ISSUE TITLE
One-to-One relationship for Litter/BreedingCage (?)

### ISSUE THREAD

**Issue by cxrodgers** [cxrodgers/MouseColony#32]
Given the new nomenclature that means every BreedingCage can have no more than one litter, does it make sense to make this a one-to-one relationship?
https://docs.djangoproject.com/en/1.9/topics/db/examples/one_to_one/

Will this break anything?

**Comment by cxrodgers** [comment]
To explore these issues, I marked all existing cages as "defunct" and created some fake test cages.
2000 - simple cage holding random mice, no breeding
2001 - breeding cage with a breeding pair, no litter yet
2002 - breeding cage with some pups
2003 - breeding cage with some pups that needs weaning
2004 - breeding cage post-weaning
2005 - new cage created with the mom from 2004 after weaning

Making a OneToOne relationship BreedingCage<->Litter seems to fit these data well. Hopefully I could add the pups directly on the BreedingCage page rather than clicking through to a Litter subpage, which would be nice. I like that it feels less "nested" than the previous structure with multiple litters per cage.

However, the distinction between Cage and BreedingCage doesn't make as much sense anymore. It's weird that 2004 is still a breeding cage, but contains no actual breeders. There are also various times when I end up at the "Cage" page when I want to be at the "BreedingCage" page.

A BreedingCage was previously defined by a "father" and "mother", but it now feels like these should be attributes of Litter, in which case there is no longer a need for distinguishing Cage and BreedingCage. We can have one object, Cage, which either has or doesn't have a Litter.

A few stray observations about the process of adding the data:
- Litter name is not necessary anymore
- When adding mice to a litter, the "Cage" attribute should default to the "BreedingCage" of that litter

**Comment by cxrodgers** [comment]
One final complication is cage-splitting into males and females. These will be new "Cage" objects, containing the appropriate mice, but with a null value for litter. Each mouse's litter attribute links back to the original breeding cage, which is now defunct.

**Comment by cxrodgers** [comment]
Data model updated
https://docs.google.com/drawings/d/1MGNAwvh41PhIuM_ZWmfc0UQKhLqRFzlC5wEJJiQGzHM/edit

**Comment by cxrodgers** [comment]
New branch to explore this modification:
https://github.com/cxrodgers/MouseColony/tree/OneToOne

**Comment by danieldkato** [comment]
To try:
1) Eliminate distinction between Cage and BreedingCage
2) The same information will be captured instead by modeling three distinct relationships between Mouse and Cage:
a) Mouse to Cage it's currently in
b) Mouse to Cage it was born in 
c) Cage(or Litter)-to-Mouse relation X-to-father/mother

This relates to a separate usability question: should we keep Litter as a separate model, or should all of the information contained therein be consolidated into Cage?

**Comment by cxrodgers** [comment]
This is implemented now in a sandbox
https://USUAL_IP/sandbox/admin

I installed nested_admin and it mostly works, except for the "Add Mouse" javascript button. There is some URLs issue with running the sandbox in a subdirectory. Nonetheless it gives a feeling of the new Cage admin page.

An alternative is to move all of the information that is in Litter into Cage, and then we don't need nested_admin anyway.

**Comment by danieldkato** [comment]
Great! This is really useful in illustrating the usability of the different options for structuring the data. 

This makes me think that maybe we should hang on to Litter as a separate model. If we move all of Litter's fields to Cage, then every instance of Cage will wind up with blank Litter-related fields even if that particular cage never contained any litters. If we keep Litter as a separate object (and set extra=0 in LitterInlineAdmin), then Litter's fields won't appear unless someone has added a litter. 

As for the "Add Mouse" javascript button, I realize now that there are two similar packages: nested-admin (https://pypi.python.org/pypi/django-nested-admin) and nested-inline (available here https://github.com/s-block/django-nested-inline). This branch is currently using the former, while I've been using the latter, and the "Add"  button works for me (in fact I think I may have even switched over after having this exact problem).

**Comment by cxrodgers** [comment]
All right, merged the OneToOne branch into master. The old database had to be nuked because the data model is so different, but made a backup copy. There is now only "Cage", and it contains a one-to-one link to litter, with admin interface implemented with nested_inline.
