### ISSUE TITLE
Instructions on each admin page

### ISSUE THREAD

**Issue by cxrodgers** [cxrodgers/MouseColony#4]
Can we have a brief paragraph of documentation / instructions on the top of each admin page explaining what the user can do on that page

**Comment by danieldkato** [comment]
Commit d37cc62 defines a fieldsets attribute (a dictionary object) for the Mouse model admin. The fieldsets dictionary includes an entry for 'description', which appears as a string above all of the included fields - for the time being, I've just set it to some placeholder text.

**Comment by cxrodgers** [comment]
Great! Now that you've figured out how to do this, we can just add the instructions to each page as it comes up. Maybe as we're training people to use it. So I'll close it.
