### ISSUE TITLE
Should Task reference Cage or Mouse or both?

### ISSUE THREAD

**Issue by cxrodgers** [cxrodgers/MouseColony#8]
Some Tasks might reference a specific Mouse, others might refer to a Cage. Not really sure how we're planning on using Tasks.

**Comment by cxrodgers** [comment]
Also would be nice if the admin view for Task showed a text output for Cage instead of the multi-select list

**Comment by danieldkato** [comment]
Commit fb240d1 gives the Task model a custom cage_names method that joins the names of the cage objects into a string. This custom method replaces the many-to-many field in the TaskAdmin, thereby showing a string instead of the mulit-select list in the admin list view.
